-- Tabla RAW DATA: Datos sin procesar de diabetes
CREATE TABLE IF NOT EXISTS diabetes_raw (
    id SERIAL PRIMARY KEY,
    batch_number INTEGER NOT NULL,
    encounter_id INTEGER,
    patient_nbr INTEGER,
    race TEXT,
    gender TEXT,
    age TEXT,
    weight TEXT,
    admission_type_id INTEGER,
    discharge_disposition_id INTEGER,
    admission_source_id INTEGER,
    time_in_hospital INTEGER,
    payer_code TEXT,
    medical_specialty TEXT,
    num_lab_procedures INTEGER,
    num_procedures INTEGER,
    num_medications INTEGER,
    number_outpatient INTEGER,
    number_emergency INTEGER,
    number_inpatient INTEGER,
    diag_1 TEXT,
    diag_2 TEXT,
    diag_3 TEXT,
    number_diagnoses INTEGER,
    max_glu_serum TEXT,
    a1cresult TEXT,
    metformin TEXT,
    repaglinide TEXT,
    nateglinide TEXT,
    chlorpropamide TEXT,
    glimepiride TEXT,
    acetohexamide TEXT,
    glipizide TEXT,
    glyburide TEXT,
    tolbutamide TEXT,
    pioglitazone TEXT,
    rosiglitazone TEXT,
    acarbose TEXT,
    miglitol TEXT,
    troglitazone TEXT,
    tolazamide TEXT,
    examide TEXT,
    citoglipton TEXT,
    insulin TEXT,
    glyburide_metformin TEXT,
    glipizide_metformin TEXT,
    glimepiride_pioglitazone TEXT,
    metformin_rosiglitazone TEXT,
    metformin_pioglitazone TEXT,
    change TEXT,
    diabetesmed TEXT,
    readmitted TEXT,
    ingested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    row_hash TEXT UNIQUE,
    split_type TEXT DEFAULT 'train' -- train, validation, test
);

CREATE INDEX IF NOT EXISTS idx_diabetes_raw_batch ON diabetes_raw (batch_number);
CREATE INDEX IF NOT EXISTS idx_diabetes_raw_split ON diabetes_raw (split_type);

-- Tabla CLEAN DATA: Datos procesados listos para entrenamiento
CREATE TABLE IF NOT EXISTS diabetes_clean (
    id SERIAL PRIMARY KEY,
    encounter_id INTEGER,
    patient_nbr INTEGER,
    race TEXT,
    gender TEXT,
    age_numeric INTEGER,
    admission_type_id INTEGER,
    discharge_disposition_id INTEGER,
    admission_source_id INTEGER,
    time_in_hospital INTEGER,
    num_lab_procedures INTEGER,
    num_procedures INTEGER,
    num_medications INTEGER,
    number_outpatient INTEGER,
    number_emergency INTEGER,
    number_inpatient INTEGER,
    number_diagnoses INTEGER,
    max_glu_serum_encoded INTEGER,
    a1cresult_encoded INTEGER,
    change_encoded INTEGER,
    diabetesmed_encoded INTEGER,
    num_diabetes_meds INTEGER,
    readmitted TEXT,
    split_type TEXT,
    processed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_diabetes_clean_split ON diabetes_clean (split_type);

-- Tabla para tracking de experimentos (opcional, MLflow maneja esto)
CREATE TABLE IF NOT EXISTS experiment_runs (
    id SERIAL PRIMARY KEY,
    experiment_name TEXT NOT NULL,
    run_id TEXT UNIQUE,
    model_name TEXT,
    accuracy FLOAT,
    precision_weighted FLOAT,
    recall_weighted FLOAT,
    f1_weighted FLOAT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
